//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogManagement.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlogManagementDbEntities : DbContext
    {
        public BlogManagementDbEntities()
            : base("name=BlogManagementDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CommentInfo> CommentInfoes { get; set; }
        public virtual DbSet<PostInfo> PostInfoes { get; set; }
        public virtual DbSet<ReactInfo> ReactInfoes { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
    }
}
