//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogManagement.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentInfo
    {
        public int CommentId { get; set; }
        public string CommentDetails { get; set; }
        public System.DateTime CommentTime { get; set; }
        public int CommentUser { get; set; }
        public int PostId { get; set; }
    
        public virtual PostInfo PostInfo { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
