//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogManagement.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReactInfo
    {
        public int ReactId { get; set; }
        public int Like { get; set; }
        public int DisLike { get; set; }
        public int PostId { get; set; }
    
        public virtual PostInfo PostInfo { get; set; }
    }
}
